name: Build APK via SFTP

on:
  workflow_dispatch:
    inputs:
      sftp_host:
        description: 'SFTP Host (IP или домен)'
        required: true
      sftp_port:
        description: 'SFTP Port (обычно 22)'
        required: true
        default: '22'
      sftp_user:
        description: 'SFTP Username'
        required: true
      sftp_pass:
        description: 'SFTP Password'
        required: true
      remote_path:
        description: 'Путь к файлам на сервере (напр. /home/user/project)'
        required: true
        default: '/'

jobs:
  build:
    name: Build and upload APK
    runs-on: ubuntu-latest

    steps:
    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev pkg-config sshpass
        pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Загрузка файлов с SFTP
      run: |
        mkdir -p project
        sshpass -p "${{ github.event.inputs.sftp_pass }}" \
          scp -o StrictHostKeyChecking=no -P ${{ github.event.inputs.sftp_port }} \
          ${{ github.event.inputs.sftp_user }}@${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.remote_path }}/main.py ./project/
        sshpass -p "${{ github.event.inputs.sftp_pass }}" \
          scp -o StrictHostKeyChecking=no -P ${{ github.event.inputs.sftp_port }} \
          ${{ github.event.inputs.sftp_user }}@${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.remote_path }}/buildozer.spec ./project/

    - name: Сборка APK
      working-directory: ./project
      run: |
        buildozer android debug

    - name: Отправка APK на SFTP
      working-directory: ./project/bin
      run: |
        sshpass -p "${{ github.event.inputs.sftp_pass }}" \
          scp -o StrictHostKeyChecking=no -P ${{ github.event.inputs.sftp_port }} \
          *.apk ${{ github.event.inputs.sftp_user }}@${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.remote_path }}/