name: Build APK via SFTP

on:
  workflow_dispatch:
    inputs:
      sftp_host:
        description: 'SFTP Host (IP или домен)'
        required: true
      sftp_port:
        description: 'SFTP Port'
        required: true
        default: '22'
      sftp_user:
        description: 'SFTP Username'
        required: true
      sftp_pass:
        description: 'SFTP Password'
        required: true

jobs:
  build:
    name: Build and upload APK
    runs-on: ubuntu-latest

    steps:
    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev pkg-config sshpass rsync
        pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Загрузка ВСЕГО ПРОЕКТА С СЕРВЕРА
      run: |
        mkdir -p project
        sshpass -p "${{ github.event.inputs.sftp_pass }}" \
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ github.event.inputs.sftp_port }}" \
          ${{ github.event.inputs.sftp_user }}@${{ github.event.inputs.sftp_host }}: ./project/

    - name: Проверка что все скачалось
      run: |
        echo "Содержимое проекта:"
        ls -laR ./project
        echo "Если тут нет файлов - ПИЗДЕЦ"

    - name: Сборка APK
      working-directory: ./project
      run: |
        buildozer android debug

    - name: Отправка APK на сервер
      run: |
        sshpass -p "${{ github.event.inputs.sftp_pass }}" \
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ github.event.inputs.sftp_port }}" \
          ./project/bin/*.apk \
          ${{ github.event.inputs.sftp_user }}@${{ github.event.inputs.sftp_host }}:/