name: Build APK via Pure SFTP

on:
  workflow_dispatch:
    inputs:
      sftp_host:
        description: 'SFTP Host (IP или домен)'
        required: true
      sftp_port:
        description: 'SFTP Port'
        required: true
        default: '22'
      sftp_user:
        description: 'SFTP Username'
        required: true
      sftp_pass:
        description: 'SFTP Password'
        required: true

jobs:
  build:
    name: Build and upload APK
    runs-on: ubuntu-latest

    steps:
    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev pkg-config lftp libtool-bin
        pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Скачивание проекта
      run: |
        mkdir -p project
        lftp -u "${{ github.event.inputs.sftp_user }},${{ github.event.inputs.sftp_pass }}" \
          sftp://${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.sftp_port }} <<EOF
        set sftp:auto-confirm yes
        mirror --verbose --parallel=10 "${{ github.event.inputs.remote_dir }}" ./project/
        quit
        EOF

    - name: Установка Android SDK
      run: |
        # Создаем директории
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        
        # Скачиваем cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        mv $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        
        # Настраиваем переменные окружения
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        
        # Принимаем лицензии
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg
        yes | sdkmanager --licenses
        
        # Устанавливаем необходимые компоненты
        sdkmanager "platform-tools" "platforms;android-21" "build-tools;36.0.0"

        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Сборка APK
      working-directory: ./project
      run: |
        buildozer android debug

    - name: Отправка APK на сервер
      run: |
        lftp -u "${{ github.event.inputs.sftp_user }},${{ github.event.inputs.sftp_pass }}" \
          sftp://${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.sftp_port }} <<EOF
        set sftp:auto-confirm yes
        mkdir -p "${{ github.event.inputs.remote_dir }}"
        mirror --reverse --verbose --parallel=10 ./project/bin/ "${{ github.event.inputs.remote_dir }}/"
        quit
        EOF