name: Build APK via Pure SFTP

on:
  workflow_dispatch:
    inputs:
      sftp_host:
        description: 'SFTP Host (IP или домен)'
        required: true
      sftp_port:
        description: 'SFTP Port'
        required: true
        default: '22'
      sftp_user:
        description: 'SFTP Username'
        required: true
      sftp_pass:
        description: 'SFTP Password'
        required: true

jobs:
  build:
    name: Build and upload APK
    runs-on: ubuntu-latest

    steps:
    - name: Установка зависимостей
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev pkg-config lftp
        pip install --upgrade pip
        pip install cython virtualenv buildozer

    - name: Скачивание проекта
      run: |
        mkdir -p project
        lftp -u "${{ github.event.inputs.sftp_user }},${{ github.event.inputs.sftp_pass }}" \
          sftp://${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.sftp_port }} <<EOF
        set sftp:auto-confirm yes
        mirror --verbose --parallel=10 "${{ github.event.inputs.remote_dir }}" ./project/
        quit
        EOF

    - name: Первый запуск сборки (инициализация SDK)
      working-directory: ./project
      run: |
        # Запускаем сборку, игнорируя ошибку лицензий
        buildozer android debug || true

    - name: Фикс лицензий Android SDK
      run: |
        # Ждем пока SDK установится
        sleep 10
        
        # ЕБАНЫЕ ЛИЦЕНЗИИ GOOGLE
        mkdir -p "$HOME/.android/licenses"
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$HOME/.android/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$HOME/.android/licenses/android-sdk-license"
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$HOME/.android/licenses/android-sdk-license"
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$HOME/.android/licenses/android-sdk-preview-license"
        
        # Автоматическое подтверждение через expect
        sudo apt-get install -y expect
        echo '#!/usr/bin/expect -f
        spawn $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        expect {
            "y/N" { exp_send "y\r"; exp_continue }
            eof
        }
        ' > accept_licenses.exp
        chmod +x accept_licenses.exp
        ./accept_licenses.exp

    - name: Сборка APK
      working-directory: ./project
      run: |
        buildozer android debug

    - name: Отправка APK на сервер
      run: |
        lftp -u "${{ github.event.inputs.sftp_user }},${{ github.event.inputs.sftp_pass }}" \
          sftp://${{ github.event.inputs.sftp_host }}:${{ github.event.inputs.sftp_port }} <<EOF
        set sftp:auto-confirm yes
        mkdir -p "${{ github.event.inputs.remote_dir }}"
        mirror --reverse --verbose --parallel=10 ./project/bin/ "${{ github.event.inputs.remote_dir }}/"
        quit
        EOF